package com.klay.model;

public class Video {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.video_id
     *
     * @mbggenerated
     */
    private String videoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.video_title
     *
     * @mbggenerated
     */
    private String videoTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.video_path
     *
     * @mbggenerated
     */
    private String videoPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.video_cover_path
     *
     * @mbggenerated
     */
    private String videoCoverPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.video_watch_count
     *
     * @mbggenerated
     */
    private Integer videoWatchCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.video_type
     *
     * @mbggenerated
     */
    private String videoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.video_id
     *
     * @return the value of video.video_id
     *
     * @mbggenerated
     */
    public String getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.video_id
     *
     * @param videoId the value for video.video_id
     *
     * @mbggenerated
     */
    public void setVideoId(String videoId) {
        this.videoId = videoId == null ? null : videoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.video_title
     *
     * @return the value of video.video_title
     *
     * @mbggenerated
     */
    public String getVideoTitle() {
        return videoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.video_title
     *
     * @param videoTitle the value for video.video_title
     *
     * @mbggenerated
     */
    public void setVideoTitle(String videoTitle) {
        this.videoTitle = videoTitle == null ? null : videoTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.video_path
     *
     * @return the value of video.video_path
     *
     * @mbggenerated
     */
    public String getVideoPath() {
        return videoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.video_path
     *
     * @param videoPath the value for video.video_path
     *
     * @mbggenerated
     */
    public void setVideoPath(String videoPath) {
        this.videoPath = videoPath == null ? null : videoPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.video_cover_path
     *
     * @return the value of video.video_cover_path
     *
     * @mbggenerated
     */
    public String getVideoCoverPath() {
        return videoCoverPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.video_cover_path
     *
     * @param videoCoverPath the value for video.video_cover_path
     *
     * @mbggenerated
     */
    public void setVideoCoverPath(String videoCoverPath) {
        this.videoCoverPath = videoCoverPath == null ? null : videoCoverPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.video_watch_count
     *
     * @return the value of video.video_watch_count
     *
     * @mbggenerated
     */
    public Integer getVideoWatchCount() {
        return videoWatchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.video_watch_count
     *
     * @param videoWatchCount the value for video.video_watch_count
     *
     * @mbggenerated
     */
    public void setVideoWatchCount(Integer videoWatchCount) {
        this.videoWatchCount = videoWatchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.video_type
     *
     * @return the value of video.video_type
     *
     * @mbggenerated
     */
    public String getVideoType() {
        return videoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.video_type
     *
     * @param videoType the value for video.video_type
     *
     * @mbggenerated
     */
    public void setVideoType(String videoType) {
        this.videoType = videoType == null ? null : videoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.user_id
     *
     * @return the value of video.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.user_id
     *
     * @param userId the value for video.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}