package com.klay.model;

public class VideoLike {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_like.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_like.video_id
     *
     * @mbggenerated
     */
    private String videoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_like.user_id
     *
     * @return the value of video_like.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_like.user_id
     *
     * @param userId the value for video_like.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_like.video_id
     *
     * @return the value of video_like.video_id
     *
     * @mbggenerated
     */
    public String getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_like.video_id
     *
     * @param videoId the value for video_like.video_id
     *
     * @mbggenerated
     */
    public void setVideoId(String videoId) {
        this.videoId = videoId == null ? null : videoId.trim();
    }
}